platform :ios, '12.0'

target 'SurveyMaster' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SurveyMaster
    pod 'SwiftyJSON'
    pod 'Alamofire'
    pod 'SVProgressHUD'
    pod 'GSMessages'
    pod 'ChameleonFramework'
    pod 'SwiftMoment'
    pod 'Wrap'
    pod 'RealmSwift'
    pod 'Charts'
end
