module.exports = {
    QUESTION_TEXT: 'QUESTION_TEXT',
    QUESTION_PARAGRAPH: 'QUESTION_PARAGRAPH',
    QUESTION_RADIO_GROUP: 'QUESTION_RADIO_GROUP',
    QUESTION_CHECKBOX: 'QUESTION_CHECKBOX',
    QUESTION_DROPDOWN: 'QUESTION_DROPDOWN',
    QUESTION_SLIDER: 'QUESTION_SLIDER',
    QUESTION_RATING: 'QUESTION_RATING',
    QUESTION_RANGE: 'QUESTION_RANGE',
    QUESTION_UPLOADFILE: 'QUESTION_UPLOADFILE',


    ANSWER_TEXT: 'ANSWER_TEXT',
    ANSWER_MULTIPLE_CHOICE: 'ANSWER_MULTIPLE_CHOICE',
    ANSWER_SINGLE_NUMBER_VALUE: 'ANSWER_SINGLE_NUMBER_VALUE',
    ANSWER_RANGE: 'ANSWER_RANGE',
    ANSWER_File_Base64: 'ANSWER_File_Base64',

    INPUT_TEXT: 'INPUT_TEXT',
    INPUT_EMAIL: 'INPUT_EMAIL',
    INPUT_NUMERIC: 'INPUT_NUMERIC',
    INPUT_PHONE_NUMBER: 'INPUT_PHONE_NUMBER',

    RATING_STARS: 'RATING_STARS',
    RATING_NUMBERS: 'RATING_NUMBERS'
}